# Generated by Django 4.2.11 on 2024-06-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacancyPosts', '0002_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edits',
            field=models.IntegerField(default=0),
        ),
    ]
